### ISSUE TITLE
KeyError: 'Ses01F_impro01_M005'

### ISSUE THREAD

**Issue by bagustris** [makhilbabu/multi-modal-emotion-recognition#1]
I got that error when running feature_extraction inside speech dir.
`KeyError: 'Ses01F_impro01_M005'`
Here my complete terminal output:
~~~     
bta@ais:speech$ python feature_extraction.py mfcc
Using TensorFlow backend.
Traceback (most recent call last):
  File "feature_extraction.py", line 80, in <module>
    llf = LowLevelFeat()
  File "feature_extraction.py", line 14, in __init__
    self.data = speech_feat_extract(sess, folderpath)
  File "/media/bagus/data01/github/multi-modal-emotion-recognition/speech/features.py", line 55, in __init__
    self.wavpaths = self.filepath_helper('/sentences/wav', '.wav')
  File "/media/bagus/data01/github/multi-modal-emotion-recognition/speech/features.py", line 90, in filepath_helper
    if f.endswith(filetype) and self.id2label[f[:-4]] in self.category_list:
KeyError: 'Ses01F_impro01_M005'
~~~

I uncomment line 79-80 on the feature_extraction.py and set the iemocap dir in the path. Something I miss for the setup?

**Comment by bagustris** [comment]
I solved this issue by removing "all" on the line 45 in features.py
from:
           `for subdir, dirs, files in os.walk(datapath + session + '/dialog/EmoEvaluation/all'):`
to:
           ` for subdir, dirs, files in os.walk(datapath + session + '/dialog/EmoEvaluation/'):`

I think there is no `all` dir in the originial iemocap dataset, maybe this is your setup.
